cards/urls.py
from django.conf.urls import url
from . import views #get current dir views

urlpatterns = [
    #/cards/
    url(r'^$', views.index, name='index'),

    #/cards/add
    url(r'^add/$', views.CardCreate.as_view(), name='card-add'),

    #/cards/2/
    url(r'(?P<pk>[0-9]+)/$', views.CardUpdate.as_view(), name='card-update'),

]

heroku/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^cards/', include('cards.urls',namespace='cards')),
    url(r'^$', RedirectView.as_view(url='/cards/', permanent=True)),
]

cards/models.py
from django.db import models

# Create your models here.
class Cubelist(models.Model):
    card_id = models.BigAutoField(primary_key=True)
    card_name = models.CharField(max_length=150)
    card_cost = models.SmallIntegerField(blank=True, null=True)
    card_image = models.CharField(max_length=200, blank=True, null=True)
    class Meta:
        managed = True
        db_table = 'cubeList'
    def __str__(self):
        return self.card_name

cards/views.py
from django.shortcuts import render
from .models import Cubelist
from django.template import loader
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView

# Create your views here.

def index(request):
    all_cards = Cubelist.objects.all()
    template = loader.get_template('cards/index.html')
    query = request.GET.get("q")
    if query:
        try:
            int(query)
            all_cards = all_cards.filter(card_cost__icontains=query)
        except ValueError:
            all_cards = all_cards.filter(card_name__icontains=query)
    #info for template
    count = (all_cards.count())
    context = {'all_cards':all_cards, 'count': count}

    return HttpResponse(template.render(context,request))

class CardCreate(CreateView):
    model = Cubelist
    fields = ['card_name', 'card_cost', 'card_image']

class CardUpdate(UpdateView):
    model = Cubelist
    fields = ['card_name', 'card_cost', 'card_image']

cards/templates/cards/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Tim's Cube{% endblock %}</title>
    {%load staticfiles%}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" type="text/css" href="{%static 'cards/css/styles.css'%}"/>
    <link rel="shortcut icon" href="{%static 'cards/css/fav-icon.jpg'%}">

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-targer="#topNavBar">
                <i class="fa fa-reorder"></i>
            </button>
            <a class="navbar-brand" href="{%url 'cards:index'%}">mtgCUBE</a>
        </div>
        <!--items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{%url 'cards:index'%}">
                        <span class="glyphicon glyphicon-inbox" aria-hidden="true"></span>&nbsp;&nbsp;Cards
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-text navbar-left display">
                <li> Cards Displayed: {{ count }} </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <!--<a href="{# {% url 'music:album-add' %}  #}">-->
                    <a href="{% url 'cards:card-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;&nbsp;Add Card
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;&nbsp;Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{%block body%}
{%endblock%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

cards/templates/cards/cubelist_form.html
{% extends 'cards/base.html' %}
{% block title %}Add a New Card{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'cards/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cards/templates/cards/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

cards/templates/cards/index.html
{% extends 'cards/base.html' %}

{%block body%}
    <div class="albums-container container-fluid">
        {% if all_cards %}
                {% for card in all_cards %}
                <div class="col-xs-12 col-sm-4 col-lg-3 holder">
                    <div class="thumbnail">
                        <a href="{# {% url 'cards:detail' card.card_id %} #}{{ card.card_image }}">
                            <img src="{{ card.card_image}}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h3>{{ card.card_name }}</h3>
                            <h5>Mana Cost - {{ card.card_cost }}</h5>
                        </div>
                    </div>
                </div>
                {# {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %} #}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{# {% url 'music:album-add' %} #}#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
{%endblock%}